///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TrackListModalPrimaryMusicListGenre {
/*
{
  "music_genre_id": 34,
  "music_genre_parent_id": 0,
  "music_genre_name": "Music",
  "music_genre_name_extended": "Music",
  "music_genre_vanity": "Music"
}
*/

  int? musicGenreId;
  int? musicGenreParentId;
  String? musicGenreName;
  String? musicGenreNameExtended;
  String? musicGenreVanity;

  TrackListModalPrimaryMusicListGenre({
    this.musicGenreId,
    this.musicGenreParentId,
    this.musicGenreName,
    this.musicGenreNameExtended,
    this.musicGenreVanity,
  });
  TrackListModalPrimaryMusicListGenre.fromJson(Map<String, dynamic> json) {
    musicGenreId = json["music_genre_id"]?.toInt();
    musicGenreParentId = json["music_genre_parent_id"]?.toInt();
    musicGenreName = json["music_genre_name"]?.toString();
    musicGenreNameExtended = json["music_genre_name_extended"]?.toString();
    musicGenreVanity = json["music_genre_vanity"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["music_genre_id"] = musicGenreId;
    data["music_genre_parent_id"] = musicGenreParentId;
    data["music_genre_name"] = musicGenreName;
    data["music_genre_name_extended"] = musicGenreNameExtended;
    data["music_genre_vanity"] = musicGenreVanity;
    return data;
  }
}

class TrackListModalPrimaryGenresMusicGenreList {
/*
{
  "music_genre": {
    "music_genre_id": 34,
    "music_genre_parent_id": 0,
    "music_genre_name": "Music",
    "music_genre_name_extended": "Music",
    "music_genre_vanity": "Music"
  }
}
*/

  TrackListModalPrimaryMusicListGenre? musicGenre;

  TrackListModalPrimaryGenresMusicGenreList({
    this.musicGenre,
  });
  TrackListModalPrimaryGenresMusicGenreList.fromJson(
      Map<String, dynamic> json) {
    musicGenre = (json["music_genre"] != null)
        ? TrackListModalPrimaryMusicListGenre.fromJson(json["music_genre"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (musicGenre != null) {
      data["music_genre"] = musicGenre!.toJson();
    }
    return data;
  }
}

class TrackListModalPrimaryGenres {
/*
{
  "music_genre_list": [
    {
      "music_genre": {
        "music_genre_id": 34,
        "music_genre_parent_id": 0,
        "music_genre_name": "Music",
        "music_genre_name_extended": "Music",
        "music_genre_vanity": "Music"
      }
    }
  ]
}
*/

  List<TrackListModalPrimaryGenresMusicGenreList?>? musicGenreList;

  TrackListModalPrimaryGenres({
    this.musicGenreList,
  });
  TrackListModalPrimaryGenres.fromJson(Map<String, dynamic> json) {
    if (json["music_genre_list"] != null) {
      final v = json["music_genre_list"];
      final arr0 = <TrackListModalPrimaryGenresMusicGenreList>[];
      v.forEach((v) {
        arr0.add(TrackListModalPrimaryGenresMusicGenreList.fromJson(v));
      });
      musicGenreList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (musicGenreList != null) {
      final v = musicGenreList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["music_genre_list"] = arr0;
    }
    return data;
  }
}

class TrackListModal {
/*
{
  "track_id": 223550307,
  "track_name": "My Universe",
  "track_name_translation_list": [
    null
  ],
  "track_rating": 99,
  "commontrack_id": 133582252,
  "instrumental": 0,
  "explicit": 0,
  "has_lyrics": 1,
  "has_subtitles": 1,
  "has_richsync": 1,
  "num_favourite": 44,
  "album_id": 46885002,
  "album_name": "My Universe - Single",
  "artist_id": 1039,
  "artist_name": "Coldplay",
  "track_share_url": "https://www.musixmatch.com/lyrics/Coldplay/My-Universe-1?utm_source=application&utm_campaign=api&utm_medium=n%2Fa%3A1409620463618",
  "track_edit_url": "https://www.musixmatch.com/lyrics/Coldplay/My-Universe-1/edit?utm_source=application&utm_campaign=api&utm_medium=n%2Fa%3A1409620463618",
  "restricted": 0,
  "updated_time": "2021-09-24T15:35:33Z",
  "primary_genres": {
    "music_genre_list": [
      {
        "music_genre": {
          "music_genre_id": 34,
          "music_genre_parent_id": 0,
          "music_genre_name": "Music",
          "music_genre_name_extended": "Music",
          "music_genre_vanity": "Music"
        }
      }
    ]
  }
}
*/

  int? trackId;
  String? trackName;
  // List<TrachListModalTrackNameTranslationList> trackNameTranslationList;
  int? trackRating;
  int? commontrackId;
  int? instrumental;
  int? explicit;
  int? hasLyrics;
  int? hasSubtitles;
  int? hasRichsync;
  int? numFavourite;
  int? albumId;
  String? albumName;
  int? artistId;
  String? artistName;
  String? trackShareUrl;
  String? trackEditUrl;
  int? restricted;
  String? updatedTime;
  TrackListModalPrimaryGenres? primaryGenres;

  TrackListModal({
    this.trackId,
    this.trackName,
    // this.trackNameTranslationList,
    this.trackRating,
    this.commontrackId,
    this.instrumental,
    this.explicit,
    this.hasLyrics,
    this.hasSubtitles,
    this.hasRichsync,
    this.numFavourite,
    this.albumId,
    this.albumName,
    this.artistId,
    this.artistName,
    this.trackShareUrl,
    this.trackEditUrl,
    this.restricted,
    this.updatedTime,
    this.primaryGenres,
  });
  TrackListModal.fromJson(Map<String, dynamic> json) {
    trackId = json["track_id"]?.toInt();
    trackName = json["track_name"]?.toString();
    trackRating = json["track_rating"]?.toInt();
    commontrackId = json["commontrack_id"]?.toInt();
    instrumental = json["instrumental"]?.toInt();
    explicit = json["explicit"]?.toInt();
    hasLyrics = json["has_lyrics"]?.toInt();
    hasSubtitles = json["has_subtitles"]?.toInt();
    hasRichsync = json["has_richsync"]?.toInt();
    numFavourite = json["num_favourite"]?.toInt();
    albumId = json["album_id"]?.toInt();
    albumName = json["album_name"]?.toString();
    artistId = json["artist_id"]?.toInt();
    artistName = json["artist_name"]?.toString();
    trackShareUrl = json["track_share_url"]?.toString();
    trackEditUrl = json["track_edit_url"]?.toString();
    restricted = json["restricted"]?.toInt();
    updatedTime = json["updated_time"]?.toString();
    primaryGenres = (json["primary_genres"] != null)
        ? TrackListModalPrimaryGenres.fromJson(json["primary_genres"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["track_id"] = trackId;
    data["track_name"] = trackName;
    data["track_rating"] = trackRating;
    data["commontrack_id"] = commontrackId;
    data["instrumental"] = instrumental;
    data["explicit"] = explicit;
    data["has_lyrics"] = hasLyrics;
    data["has_subtitles"] = hasSubtitles;
    data["has_richsync"] = hasRichsync;
    data["num_favourite"] = numFavourite;
    data["album_id"] = albumId;
    data["album_name"] = albumName;
    data["artist_id"] = artistId;
    data["artist_name"] = artistName;
    data["track_share_url"] = trackShareUrl;
    data["track_edit_url"] = trackEditUrl;
    data["restricted"] = restricted;
    data["updated_time"] = updatedTime;
    if (primaryGenres != null) {
      data["primary_genres"] = primaryGenres!.toJson();
    }
    return data;
  }
}
