///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TrackDetailLyricsModal {
/*
{
  "lyrics_id": 26492981,
  "explicit": 0,
  "lyrics_body": "You (you), you are (you are) my universe\nAnd I (and I) just want (just want) to put you first\nAnd you (you), you are (you are) my universe, and I\n\nIn the night, I lie and look up at you\nWhen the morning comes, I watch you rise\nThere's a paradise they couldn't capture\nThat bright infinity inside your eyes\n\n매일 밤 네게 날아가 (가)\n꿈이란 것도 잊은 채\n나 웃으며 너를 만나 (나)\nNever ending forever, baby\n\nYou (you), you are (you are) my universe\nAnd I (I), just want (just want) to put you first (to put you first)\nAnd you (you), you are (you are) my universe\nAnd you make my world light up inside\n\n...\n\n******* This Lyrics is NOT for Commercial use *******\n(1409620463618)",
  "script_tracking_url": "https://tracking.musixmatch.com/t1.0/m_js/e_1/sn_0/l_26492981/su_0/rs_0/tr_3vUCAFDPPC9jWfwGzpPAPlRoPo58o762IljZddVdjB2_sgdSLM7OvROmEy_djPEy31bOTcwkAV7cZUR9DU5ALnKykqyrh66lpu6eKB0bY5KGmlJrqFRcdDN6sMBpYmUwTmjvI0pMcLaN4s4tFzmTh-n2vpgUu86czG75cY_S76lAstyvSeWFyb4e4Zly0kgBmsPPzBU3A1_cFsypWVguwHIKia_HHM7vulyBjS-zl-2DI-j-Pd_AQiQWFRyq9RWMAgv-4W8pgTPIxAbtWF_sR0gJ6B58xk6FWQ3ULzQdiIj26u2LBM7TIB7QzbXbmyYQWiE1uI6SZihb3-eNrAghF1B66o27eg0MbXHuotF5BfpdC7pWB3h5_PLZJGhuECkTsBZi7-tw089PvRu_rvY5xbk08o7wb7ghACerc874zuO0Tei8HCWQ6s7W2bR9bFCxKw/",
  "pixel_tracking_url": "https://tracking.musixmatch.com/t1.0/m_img/e_1/sn_0/l_26492981/su_0/rs_0/tr_3vUCADmrrV2400Iz-eB4YJ1an7s2bYgX_Re49n04DsyTf5LxSEw6fnGTUwWof9ZaKGDz9zACpZkNRFyktkOR-txTZk-En5cBlZ2nm7UXFRohEF5CXuv1_qN82qx-p985d36d6z5cPXlCqasGx_KH3nY4GI7_cxPWpgIzt7RFiSqV2jLtbTqL1npsRPiaVxc4F_pqi7MVFvVdNz0d3waeolUCTRqAtH7Pq55J8uhdpfaCCoaHEpS558HI_xjMZifzQujx3i6rJhdSiWLXdfxqCky9RWzf71giTi-Bq2s44OZ_8-7Wi4diY2H9I2lTQNgXyMpe_LOskjyfbfSkorYoxmonVZSbKdqEVu97hEBhfWRUkrGK1kLoGVonwTgY77h6tVAzKbH2KXPpiOaFDmqHxeioD-U9uWuN6e6bRyOAmgVAN_CPOMH5sg33SoX1DZxwtA/",
  "lyrics_copyright": "Lyrics powered by www.musixmatch.com. This Lyrics is NOT for Commercial use and only 30% of the lyrics are returned.",
  "updated_time": "2021-09-24T15:35:32Z"
}
*/

  int? lyricsId;
  int? explicit;
  String? lyricsBody;
  String? scriptTrackingUrl;
  String? pixelTrackingUrl;
  String? lyricsCopyright;
  String? updatedTime;

  TrackDetailLyricsModal({
    this.lyricsId,
    this.explicit,
    this.lyricsBody,
    this.scriptTrackingUrl,
    this.pixelTrackingUrl,
    this.lyricsCopyright,
    this.updatedTime,
  });
  TrackDetailLyricsModal.fromJson(Map<String, dynamic> json) {
    lyricsId = json["lyrics_id"]?.toInt();
    explicit = json["explicit"]?.toInt();
    lyricsBody = json["lyrics_body"]?.toString();
    scriptTrackingUrl = json["script_tracking_url"]?.toString();
    pixelTrackingUrl = json["pixel_tracking_url"]?.toString();
    lyricsCopyright = json["lyrics_copyright"]?.toString();
    updatedTime = json["updated_time"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["lyrics_id"] = lyricsId;
    data["explicit"] = explicit;
    data["lyrics_body"] = lyricsBody;
    data["script_tracking_url"] = scriptTrackingUrl;
    data["pixel_tracking_url"] = pixelTrackingUrl;
    data["lyrics_copyright"] = lyricsCopyright;
    data["updated_time"] = updatedTime;
    return data;
  }
}
